### ISSUE TITLE
TCL Issue?

### ISSUE THREAD

**Issue by fnordson** [michaelortmann/megahal.mod#1]
First: thank you for providing this working version of MegaHAL. 
I had to update my pi and using the old installation files failed due to the 32bit issue. 

Now, I compiled with your mod file, bot is there and connected. Everything looks file but it doesn't react to their prompt. 
Now since I took the old .tcl file I guess it might be an issue with that one. 
I forgot how all of this works and there are no proper guides out there so I don't know where to go from here on. 

Is there a new .tcl file required? Where can I get it? 
Did I forget to set something? 
Any help would be appreciated...

**Comment by michaelortmann** [comment]
I only modified the module to run with current eggdrop version and never really used it. Maybe you can find a user of this module on irc.libera.chat #eggdrop ?

**Comment by fnordson** [comment]
Thanks. 
I'll try that.
